- hosts: all

  tasks:

    - name: Install docker
      ansible.builtin.dnf:
        name: docker
        state: present
        update_cache: true
      become: true
    - name: Start dockerd
      ansible.builtin.service:
        name: docker
        state: started
      become: true

    - name: Add user to the docker group
      ansible.builtin.user:
        name: '{{ ansible_user }}'
        groups: docker
        append: true
      become: true

    - name: Reset ssh connection to allow user/group change to take effect
      ansible.builtin.meta:
        reset_connection

    - name: Run test container
      community.docker.docker_container:
        name: testcontainer
        state: started
        image: busybox
        command: echo hello world
